### ISSUE TITLE
Make lexer generation stick to the class instead of the token-kind

### ISSUE THREAD

**Issue by LPeter1997** [LanguageDev/Yoakke#85]
**Is your feature request related to a problem? Please describe.**
Right now the lexer generator generates a fixed class we can't modify. We can't provide our own constructor, override the method, ...

**Describe the solution you'd like**
We should be able to customize the generated lexer class fully, like the parser.

**Describe alternatives you've considered**
We could externalize the `[Lexer]` attribute, and make it stick to the class we generate instead of the token-kind. It would be very similar to what we did to the visitor library recently:
```cs
[Lexer(TokenKind = typeof(TokenType))]
partial class MyLexer {}
```
A nice side-effect is getting rid of the last ugly string-encoded type name.

**Comment by LPeter1997** [comment]
@skneko you have mentioned that  on premise token definitions would also be nice, what are your thoughts on that? How would you imagine the annotations for it?

**Comment by skneko** [comment]
Ah, I think that was a misunderstanding. I meant the ability to add constructors, fields, overrides... which is already covered in the issue.

The benefits would require the class to be partial (nothing new, justice the other cases) and then the source generators need to create a parallel partial class definition.
